# -*- coding: utf-8 -*-
"""Music Splitter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdEpG81J6jPQb93nQS8FfnJC9UvhfmOP
"""

# Install FFmpeg (audio processing tool)
!apt-get install -y ffmpeg

# Install TensorFlow and Spleeter
!pip install spleeter

from google.colab import files

print(" Please upload an audio file (MP3 or WAV)")
uploaded = files.upload()

# Upload file name
filename = list(uploaded.keys())[0]
print(f" File uploaded: {filename}")

from spleeter.separator import Separator

# Create separator object with 2 stems (vocals + others)
separator = Separator('spleeter:2stems')

# Separate audio and save to 'output/' folder
separator.separate_to_file(filename, 'output')
print(" Separation Complete!")

import os
from google.colab import files

# Extract base filename
base_name = os.path.splitext(filename)[0]

# Construct paths
vocals_path = f'output/{base_name}/vocals.wav'
accompaniment_path = f'output/{base_name}/accompaniment.wav'

# Offer files for download
print("⬇ Preparing downloads...")
files.download(vocals_path)
files.download(accompaniment_path)

from IPython.display import Audio

print("🎧 Vocals:")
display(Audio(vocals_path))

print("🎸 Instrumental:")
display(Audio(accompaniment_path))